name: _

publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/spark
  - packages/spark/example
  - packages/spark_cli
  - packages/spark_css
  - packages/spark_generator
  - packages/spark_html_dsl
  - packages/spark_vdom
  - packages/spark_web
