name: spark_generator
description: Code generator for Spark Framework pages and components
version: 1.0.0-alpha.8
resolution: workspace

homepage: https://spark.kleak.dev
repository: https://github.com/KLEAK-Development/spark
issue_tracker: https://github.com/KLEAK-Development/spark/issues

environment:
  sdk: ^3.10.0

dependencies:
  build: ^4.0.4
  source_gen: ^4.1.2
  analyzer: ^10.0.1
  spark_framework: ^1.0.0-alpha.2
  code_builder: ^4.11.1
  glob: ^2.1.3
  path: ^1.9.1
  dart_style: ^3.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
  build_test: ^3.5.5
