name: spark_css
description: Type-safe CSS style system for Spark framework.
version: 1.0.0-alpha.1
resolution: workspace

homepage: https://spark.kleak.dev
repository: https://github.com/KLEAK-Development/spark
issue_tracker: https://github.com/KLEAK-Development/spark/issues

environment:
  sdk: ^3.10.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^6.0.0
  test: ^1.29.0
