name: spark_example
description: Example application demonstrating Spark Framework with code generation
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  shelf: ^1.4.2
  spark_framework: ^1.0.0-alpha.1

dev_dependencies:
  build_runner: ^2.10.5
  build_web_compilers: ^4.4.7
  spark_generator: ^1.0.0-alpha.1
  lints: ^6.0.0
